### PR TITLE
Imagespace SMQTK search

### PR DESCRIPTION
**Pull request by danlamanna**
@jeffbaumes This is based off the CMU PR #106 since I wanted the helper function here as well.

Diff this: https://github.com/memex-explorer/image_space/compare/update-cmu-plugin-for-case-sensitivity...imagespace_smqtk_search

@aashish24

### CODE REVIEW

**Comment by aashish24** [comment]
thanks @danlamanna :ghost:  I will have a look at it tonight.

**Comment by aashish24** [comment]
@danlamanna how did you test it locally?

**Comment by danlamanna** [comment]
@aashish24 I used the SMQTK service Paul setup on OpenStack, and I loaded his mapping of sha1 -> filepath into my local mongo install.

**Comment by jeffbaumes** [comment]
Code LGTM even though I have not tested this yet. If it's helpful you can go ahead and merge this.

**Pull request merged**
