### PR TITLE
UI Refactor

### PR DESCRIPTION
**Pull request by danlamanna**
@lawongsta @jeffbaumes 

This refactors some of the UI, adds styling, allows the front page search bar to also be a drop zone for uploading, moves help/about to their own static pages.

Additionally:
- Decouples a lot of elements into their own views
- Fixes the user data panel from rendering twice
- Persists the state of the unblur setting

I left the help page as a copy of what the front page was. I did this because I didn't want to add screenshots of the rest of the application until we've more or less settled on the final UI.

imagespace-ui-refactor-1
imagespace-ui-refactor-2
imagespace-ui-refactor-3

### CODE REVIEW

**Comment by jeffbaumes** [comment]
@danlamanna screenshot update plz?

**Comment by jeffbaumes** [comment]
In general whenever you push new commits to a PR and want people to take a look - please add a comment to the PR, otherwise no one gets any notification.

**Comment by danlamanna** [comment]
imagespace-ui-refactor-4

@jeffbaumes!!11

Also note the drop an image part isn't applicable to logged out users.

**Comment by jeffbaumes** [comment]
What happens if a logged-out user drags an image? I think it's reasonable for the message to read "Enter a search term or log in to upload an image..." if logged out and for the upload button and drag events to be disabled - can you make that happen easily?

**Comment by danlamanna** [comment]
[Maybe..](https://github.com/memex-explorer/image_space/commit/63a8bf3e009710c07c399572044e2d712f748f91#diff-6b65c7ddc83a4b06778eb4c71f247b56L28)

**Comment by jeffbaumes** [comment]
Ok that's spooky. LGTM. @lawongsta feel free to chime in even after this is merged - we can make additional tweaks to CSS etc. but I think this is in line with what you were after.

**Comment by chrismattmann** [comment]
great work!

**Pull request merged**
