### PR TITLE
Image centric search

### PR DESCRIPTION
**Pull request by jeffbaumes**

### CODE REVIEW

**Comment by jeffbaumes** [comment]
Plenty still to do before this is merged:
- [x] Enable users to enter text search at any point - currently hidden in image-centered search
- [x] Enable image details from top bar
- [x] Show same search options in image detail widget as appears on top bar (ad, content, background, etc.)
- [x] Panel for system stuff (meta, etc.) that is collapsed by default
- [x] Ensure user-saved image search functions properly

**Comment by jeffbaumes** [comment]
@chrismattmann This is ready for review. Fairly large changes. I've updated our Memex cloud instance to this branch so you can poke around.

**Comment by jeffbaumes** [comment]
Ok this has sat long enough and it's been reviewed. Merging.

**Comment by chrismattmann** [comment]
Looks great!

**Pull request merged**
