### PR TITLE
Add ability to select gun classifications

### PR DESCRIPTION
**Pull request by danlamanna**
The threshold of .7 was determined empirically for this dataset

### CODE REVIEW

**Comment by jeffbaumes** [comment]
Code logic LGTM. Can you push this to a live version of the app to review?

**Comment by danlamanna** [comment]
It's live, feel free to test. I think there is a heisenbug somewhere in there, haven't been able to reproduce.

**Comment by jeffbaumes** [comment]
Would be nice to add a bit of space (15px) below the search control to even out the spacing, otherwise LGTM!

**Comment by danlamanna** [comment]
Done!

**Pull request merged**
