### PR TITLE
Update Georgetown REST endpoint

### PR DESCRIPTION
**Pull request by harsham05**
@chrismattmann @lewismc Thank you

### CODE REVIEW

**Comment by harsham05** [comment]
ImageSpace now leverages the new reRank algorithm developed by Georgetown.

**Comment by lewismc** [comment]
@chrismattmann @jeffbaumes I tried this PR out last week whilst at Memex and it was working fine. Whats thoughts on merging?

**Comment by chrismattmann** [comment]
Let's merge! doing now. @lewismc great work @harsham05

**Comment by lewismc** [comment]
Nice work @harsham05

**Comment by harsham05** [comment]
Thank you @lewismc @chrismattmann :)

**Comment by harsham05** [comment]
@lewismc Documentation is being prepared, will provide link soon

**Pull request merged**
