### PR TITLE
Refresh sidebar on login/logout events

### LINKED ISSUE #121: Login/Logout requires refresh to update sidebar

### PR DESCRIPTION
**Pull request by danlamanna**
This properly readjusts the sidebar when a user logs in or out, rather
than requiring a refresh.

Some extra care was needed because updating user data won't reset the
collection, added comment/todo for it.

Fixes #121

### CODE REVIEW

**Comment by danlamanna** [comment]
This isn't ready for review, there's still a bug causing the login event to be trigger twice.

**Comment by danlamanna** [comment]
@jeffbaumes Ready for review

**Comment by jeffbaumes** [comment]
It seems there is a bug. If I login and save an image from a search result, then do a logout then log back in - the image appears twice on the sidebar.

**Comment by danlamanna** [comment]
Thanks, I tested it quite a bit but didn't catch that one.

There are a couple of issues, 1 is that when it updates the user data from the server it's not idempotent.. it just keeps appending to the collection. It needs to use Backbone's smart updates to treat them as a set. And 2, `render` gets called twice in different places due to poor event handling. It shouldn't get called twice, but if updating the user data were idempotent it would still function correctly from the user perspective.

**Comment by danlamanna** [comment]
@jeffbaumes ready to review.

**Comment by jeffbaumes** [comment]
Yup, confirm that issue is gone - LGTM

**Pull request merged**
